name: weather_app
description: A Flutter weather app fetching real-time weather with OpenWeatherMap API.

publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  lottie: ^3.3.1
  intl: ^0.20.2
  geocoding: ^4.0.0
  http: 1.3.0
  geolocator: ^9.0.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sunny_background.jpg
    - assets/partly_cloudy_background.jpg
    - assets/cloudy_background.jpg
    - assets/rainy_background.jpg
    - assets/thunder_background.jpg
    - assets/humidity_background.jpg
    - assets/snow_background.jpg

  # Uncomment and configure fonts if you add any custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
